### ISSUE TITLE
header_index is -1

### ISSUE THREAD

**Issue by hengying** [Jaron0211/C8_master#1]
I'm using this library on ESP32 in PlatformIO.

C8_master.cpp line 68:
```
int header_index = _buffer.indexOf(char(0x42)+char(0x4D)+char(0x0C)+char(0x51));
```

the header_index's value is -1, and raw_data is wrong, like this:
```
0 0
1 42
2 4D
3 C
4 51
5 9
6 A2
...
12 81
13 20
14 8
15 20
```

I change code into this:
```
String _head_str = "";
_head_str += char(0x42);
_head_str += char(0x4D);
_head_str += char(0x0C);
_head_str += char(0x51);
int header_index = _buffer.indexOf(_head_str);
```

the head_index's value is 0 now, and the raw_data is correct.

**Comment by Jaron0211** [comment]
Thanks! I will update this issue. BTW, I didn't add the CRC check in msg processing function, maybe you can add by yourself.
